spring:
  profiles:
    active: dev

  config:
    import:
      - optional:classpath:application.dev.yml

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

