spring:
  profiles:
    active: dev

  config:
    import:
      - optional:classpath:application.dev.yml

  mvc:
    view:
      suffic: .html

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 80
